# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:10-jdk-node-browsers
      
    environment:
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      - run: mvn -f pismo-accounts/pom.xml clean package

      - run: mvn -f pismo-transactions/pom.xml clean package

workflows:
  version: 2
  build-and-test:
    jobs:
      - build


